[web]
host = "127.0.0.1"
port = 7010

[nats]
broker-url = "localhost"
broker-port = 4222
username = ""
password = ""

[switch]
name = "mybandswitch"
# type = "dummy_switch"
type = "multi_purpose_gpio"
# type = "stackmatch_gpio"
# type = "ea4tx_remotebox"

[mybandswitch]
name = "Bandswitch"
id = 0
exclusive = true
ports = ["port_a", "port_b"]

# Ports for myBandswitch
[port_a]
name = "A"
id = 0
exclusive = true
terminals = ["a_160m", "a_80m", "a_40m", "a_20m", "a_15m", "a_10m", "a_6m", "a_WARC"]

[port_b]
name = "B"
id = 1
exclusive = true
terminals = ["b_160m", "b_80m", "b_40m", "b_20m", "b_15m", "b_10m", "b_6m", "b_WARC"]

# Terminals (GPIO Pins) for a
[a_160m]
name = "160m"
pin = "GPIO3"
inverted = true
id = 0

[a_80m]
name = "80m"
pin = "GPIO19"
inverted = true
id = 1

[a_40m]
name = "40m"
pin = "GPIO18"
inverted = true
id = 2

[a_20m]
name = "20m"
pin = "GPIO15"
inverted = true
id = 3

[a_15m]
name = "15m"
pin = "GPIO16"
inverted = true
id = 4

[a_10m]
name = "10m"
pin = "GPIO2"
inverted = true
id = 5

[a_6m]
name = "6m"
pin = "GPIO14"
inverted = true
id = 6

[a_WARC]
name = "WARC"
pin = "GPIO13"
inverted = true
id = 7

# Terminals (GPIO Pins) for PortB
[b_160m]
name = "160m"
pin = "GPIO7"
inverted = true
id = 0

[b_80m]
name = "80m"
pin = "GPIO0"
inverted = true
id = 1

[b_40m]
name = "40m"
pin = "GPIO199"
inverted = true
id = 2

[b_20m]
name = "20m"
pin = "GPIO1"
inverted = true
id = 3

[b_15m]
name = "15m"
pin = "GPIO6"
inverted = true
id = 4

[b_10m]
name = "10m"
pin = "GPIO198"
inverted = true
id = 5

[b_6m]
name = "6m"
pin = "GPIO12"
inverted = true
id = 6

[b_WARC]
name = "WARC"
pin = "GPIO11"
inverted = true
id = 7
