[web]
host = "127.0.0.1"
port = 7010

[nats]
broker-url = "localhost"
broker-port = 4222
username = ""
password = ""

[switches]
multi_purpose_gpio = ["myBandswitch"]

[myBandswitch]
name = "Bandswitch"
id = 0
exclusive = true
ports = ["PortA", "PortB"]

# Ports for myBandswitch
[PortA]
name = "A"
id = 0
exclusive = true
terminals = ["PortA_160m", "PortA_80m", "PortA_40m", "PortA_20m", "PortA_15m", "PortA_10m", "PortA_6m", "PortA_WARC"]

[PortB]
name = "B"
id = 1
exclusive = true
terminals = ["PortB_160m", "PortB_80m", "PortB_40m", "PortB_20m", "PortB_15m", "PortB_10m", "PortB_6m", "PortB_WARC"]

# Terminals (GPIO Pins) for PortA
[PortA_160m]
name = "160m"
pin = "GPIO3"
inverted = true
id = 0

[PortA_80m]
name = "80m"
pin = "GPIO19"
inverted = true
id = 1

[PortA_40m]
name = "40m"
pin = "GPIO18"
inverted = true
id = 2

[PortA_20m]
name = "20m"
pin = "GPIO15"
inverted = true
id = 3

[PortA_15m]
name = "15m"
pin = "GPIO16"
inverted = true
id = 4

[PortA_10m]
name = "10m"
pin = "GPIO2"
inverted = true
id = 5

[PortA_6m]
name = "6m"
pin = "GPIO14"
inverted = true
id = 6

[PortA_WARC]
name = "WARC"
pin = "GPIO13"
inverted = true
id = 7

# Terminals (GPIO Pins) for PortB
[PortB_160m]
name = "160m"
pin = "GPIO7"
inverted = true
id = 0

[PortB_80m]
name = "80m"
pin = "GPIO0"
inverted = true
id = 1

[PortB_40m]
name = "40m"
pin = "GPIO199"
inverted = true
id = 2

[PortB_20m]
name = "20m"
pin = "GPIO1"
inverted = true
id = 3

[PortB_15m]
name = "15m"
pin = "GPIO6"
inverted = true
id = 4

[PortB_10m]
name = "10m"
pin = "GPIO198"
inverted = true
id = 5

[PortB_6m]
name = "6m"
pin = "GPIO12"
inverted = true
id = 6

[PortB_WARC]
name = "WARC"
pin = "GPIO11"
inverted = true
id = 7
