language: go
dist: xenial
sudo: true

matrix:
  include:
  - os: linux
    env:
    - GIMME_OS=linux
      GIMME_ARCH=amd64
      HOST_OS=linux
    go: "1.11"
  - os: linux
    env:
    - GIMME_OS=linux
    - GIMME_ARCH=386
    - HOST_OS=linux
    go: "1.11"
  - os: linux
    env:
    - GIMME_OS=linux
    - GIMME_ARCH=arm64
    - HOST_OS=linux
    go: "1.11"
  - os: linux
    env:
    - GIMME_OS=linux
    - GIMME_ARCH=arm
    - HOST_OS=linux
    go: "1.11"
  - os: linux
    env:
    - GIMME_OS=windows
    - GIMME_ARCH=amd64
    - HOST_OS=linux
    go: "1.11"
  - os: linux
    env:
    - GIMME_OS=windows
    - GIMME_ARCH=386
    - HOST_OS=linux
    go: "1.10"
  - os: osx
    env:
    - GIMME_OS=darwin
    - GIMME_ARCH=amd64
    - HOST_OS=darwin
    go: "1.11"

before_install:
- git fetch --tags
- GOARCH=amd64 GOOS=$HOST_OS go get github.com/mattn/goveralls
- GOARCH=amd64 GOOS=$HOST_OS go get github.com/GeertJohan/go.rice/rice
script:
- GOARCH=$GIMME_ARCH GOOS=$GIMME_OS go get ./...
- GOARCH=$GIMME_ARCH GOOS=$GIMME_OS ./ci/test.sh
- GOARCH=amd64 GOOS=$HOST_OS make vue_production
- GOARCH=amd64 GOOS=$HOST_OS make generate
- GOARCH=$GIMME_ARCH GOOS=$GIMME_OS make dist
# - file remoteSwitch
before_deploy:
- ./ci/pack.sh
deploy:
  provider: releases
  file_glob: true
  file: remoteSwitch-v$TRAVIS_TAG-$GIMME_OS-$GIMME_ARCH.*
  skip_cleanup: true
  api_key:
    secure: Uk/QIl32MHrKPJODC2DqPb/yv96GH+EBIqogoIGDflWdt/7mc9TvXt+YffIXVPTdzTz/XPUvH3m1otoN3VOU01+lv8uWmZY1J/G6ZG4LgaGo9m3M5DdlOBUB6bKJaDHJxNJU0qvgMDswZRPqqz+63WXmKhfwZX5E4CWwnvnNi4b9/NbpJhRUz19eg3uII8VC/tP6gdj6EsfB3fVU7u5zz95Xjwm2enV3kdMoaKxL1NpnrZ1a8qoNfF6/rX5+ODghSld2eSiYXNbxuN5z8uqLh/V9zotrQdzEHZMCS5mV0CMhRPI5afqG2HTSKKm9qsENTMhFRTjNFfTA0os7HLvGukTpCjwVUHzJQuXRC+8xucTaRy4jm6DDNk9wvaIoHLTYWKht9kblNjuonCFmYUe/vR9zn7G40wNCSykYTxjcrLRDwmbSZR7xWKGgNwwFB64g2mG+cKtwkVyg64kcq6yodd+xls7Fg5hVI4r8A7SbnH4+sJR5PaXa6xTxomlGp6airj4Jfl1MqyfiDX7KYQ6qk+9Ny2d1oc/eHbUujXo1SsGcVWUD+4RvcKHdOVchHZJV5E5cZROQqrstI/W3nRRijON+Q+wGiPvkxTGDlJ8bTSNuZ8PkVoG6Tr1e4aZzNH5wglYAILtE9BRPyQSLy4WorcKLFaIlY+irEFQJosT3svA=
  on:
    repo: dh1tw/remoteSwitch
    # tags: true
    draft: true