# This is a remoteSwitch example configuration file for a GPIO based stackmatch.
# It is configured for a SJ2W stacker-v3 with an additional relay to toggle a
# triplexor dummy load (see https://dh1tw.de/4o3a-triplexor). If you don't have
# a triplexor, just remove that pin from the respective combinations.

# SJ2W stacker-v3 (stackmatch) relay / terminal mapping
# see: http://sj2w.se/shop/?product=stacker-v3
# Ant 	A	B	C
# Relay	K1	K2	K3	STCK
# ---------------------------
# A		1	0	0	1
# B		0	1	0	1
# C		0	0	1	1
# A+B	0	0	1	0
# A+C	0	1	0	0
# B+C	1	0	0	0
# A+B+C	0	0	0	0

# Configuration for connection to the NATS broker
[nats]
broker-url = "localhost"
broker-port = 4222
username = ""
password = ""

# All remoteSwitches are at their core "switches". Here we specify the type
# and configuration key of the switch.
[switch]
name = "first_stackmatch"
type = "stackmatch_gpio"
# type = "multi_purpose_gpio"
# type = "stackmatch_gpio"
# type = "ea4tx_remotebox"

# This is the main configuration key. The name of the key is arbitrary, however
# it must be referenced corectly in the [switch] key.
[first_stackmatch]
name = "Stackmatch 20m" # name of the stackmatch
index = 1 # order (helper for consistent visualization)
# combinations refer to a list of keys holding the terminal/pin cominations
# supported by this stackmatch.
combinations = ["c_ant1", "c_ant2", "c_ant3", "c_ant1_ant2", "c_ant1_ant3", "c_ant2_ant3", "c_ant1_ant2_ant3"]

# Combination
[c_ant1]
terminals = ["ant1"]
pins = ["k1", "stck", "triplexor1"]

# Combination
[c_ant2]
terminals = ["ant2"]
pins = ["k2", "stck"]

# Combination
[c_ant3]
terminals = ["ant3"]
pins = ["k3", "stck"]

# Combination
[c_ant1_ant2]
terminals = ["ant1", "ant2"]
pins = ["k3", "triplexor1"]

# Combination
[c_ant1_ant3]
terminals = ["ant1", "ant3"]
pins = ["k2", "triplexor1"]

# Combination
[c_ant2_ant3]
terminals = ["ant2", "ant3"]
pins = ["k1"]

# Combination
[c_ant1_ant2_ant3]
terminals = ["ant1", "ant2", "ant3"]
pins = ["triplexor1"]

# Terminal (corresponds to the buttons you would see in the UI)
[ant1]
name = "OB11-3"
index = 1 #order

# Terminal
[ant2]
name = "4L"
index = 2

# Terminal
[ant3]
name = "3L@EU"
index = 3

# GPIO Pin / Relay
[k1]
inverted = true
pin = "GPIO13"

# GPIO Pin / Relay
[k2]
inverted = true
pin = "GPIO14"

# GPIO Pin / Relay
[k3]
inverted = true
pin = "GPIO2"

# GPIO Pin / Relay
[stck]
inverted = true
pin = "GPIO16"

# GPIO Pin / Relay
[triplexor1]
inverted = true
pin = "GPIO7"